<script>
export default 
  
  [
  { id: 1,
    name: 'Astra',
    role: 'Contrôleur',
    difficulty: 'Difficile',
    image: new URL('../assets/images/icons/Astra_icon.webp', import.meta.url).href ,
    text :"L'agent ghanéen Astra canalise les énergies du cosmos pour façonner le champ de bataille à sa convenance. Avec une maîtrise complète de sa forme astrale et un talent pour la planification stratégique, elle a toujours une large avance sur ses ennemis.",
    video : "https://www.youtube.com/embed/-ylVnuPWlJM"
  },
  { id: 2, 
    name: 'Breach', 
    role: 'Initiateur', 
    difficulty: 'Moyenne', 
    image: new URL('../assets/images/icons/Breach_icon.webp', import.meta.url).href,
    text :"Breach, le Suédois bionique, tire de puissantes décharges cinétiques pour ouvrir un chemin en territoire ennemi. Grâce aux dégâts et aux diversions ainsi provoqués, aucun combat n'est jamais en sa défaveur.",
    video :"https://www.youtube.com/embed/Rux0HjzKQbw"
  },
  { id: 3, 
    name: 'Brimstone', 
    role: 'Contrôleur', 
    difficulty: 'Facile', 
    image: new URL('../assets/images/icons/Brimstone_icon.webp', import.meta.url).href,
    text :"Tout droit venu des États-Unis d'Amérique, Brimstone possède un arsenal orbital qui permet à son escouade de toujours avoir l'avantage. La précision et la fiabilité de ses compétences utilitaires font de lui un commandant sans égal sur le terrain.",
    video :"https://www.youtube.com/embed/7yHnJ_oNxTI"
  },
  { id: 4, 
    name: 'Chamber', 
    role: 'Sentinelle', 
    difficulty: 'Facile', 
    image: new URL('../assets/images/icons/Chamber_icon.webp', import.meta.url).href,
    text :"Aussi classe que bien équipé, le concepteur d'armes français Chamber repousse les assaillants avec une précision mortelle. Il met à profit son arsenal bien particulier pour tenir sa position et éliminer les ennemis de loin en prévoyant une solution aux défis posés par chaque stratégie.",
    video :"https://www.youtube.com/embed/FUoqAn5T4h4"
  },
  { id: 5, 
    name: 'Clove', 
    role: 'Contrôleur', 
    difficulty: 'Facile', 
    image: new URL('../assets/images/icons/Clove_icon.webp', import.meta.url).href,
    text :"Clove, l'intenable Écossais·e, déstabilise l'ennemi dans le feu de l'action comme le froid de la mort. Iel sème le trouble dans les rangs ennemis, même depuis sa tombe, car sa mort ne dure jamais très longtemps.",
    video :"https://www.youtube.com/embed/QL0LUaxWUOI"
  },
  { id: 6, 
    name: 'Cypher', 
    role: 'Sentinelle', 
    difficulty: 'Moyenne', 
    image: new URL('../assets/images/icons/Cypher_icon.webp', import.meta.url).href,
    text :"Informateur originaire du Maroc, Cypher est un véritable réseau de surveillance à lui tout seul. Il révèle tous les secrets. Il détecte toutes les manœuvres. Rien n'échappe à Cypher.",
    video :"https://www.youtube.com/embed/SgbqFtRRgLA"
  },
  { id: 7, 
    name: 'Deadlock', 
    role: 'Sentinelle', 
    difficulty: 'Moyenne', 
    image: new URL('../assets/images/icons/Deadlock_icon.webp', import.meta.url).href,
    text :"Deadlock, l'agent spécial norvégien, déploie un éventail de nanocâbles ultra-modernes pour défendre sa position contre le plus violent des assauts. Nul n'échappe à sa vigilance, ni ne survit à sa cruelle ténacité.",
    video :"https://www.youtube.com/embed/UK7Tdob8HQw"
  },
  { id: 8, 
    name: 'Fade', 
    role: 'Initiateur', 
    difficulty: 'Moyenne', 
    image: new URL('../assets/images/icons/Fade_icon.webp', import.meta.url).href,
    text :"Originaire de Turquie, la chasseuse de primes Fade utilise le pouvoir des cauchemars pour s'emparer des secrets ennemis. Elle traque ses cibles et révèle leurs plus grandes peurs pour mieux les briser dans l'obscurité.",
    video :"https://www.youtube.com/embed/e7VOQ1l20eo"
  },
  { id: 9, 
    name: 'Gekko', 
    role: 'Initiateur', 
    difficulty: 'Moyenne', 
    image: new URL('../assets/images/icons/Gekko_icon.webp', import.meta.url).href,
    text :"Originaire de Los Angeles, Gekko dirige une bande de créatures chaotiques, mais très soudées. Ses amis s'occupent de disperser les ennemis, puis Gekko rassemble sa petite troupe pour recommencer.",
    video :"https://www.youtube.com/embed/iYFh_XAXSPk"
  },
  { id: 10, 
    name: 'Harbor', 
    role: 'Contrôleur', 
    difficulty: 'Moyenne', 
    image: new URL('../assets/images/icons/Harbor_icon.webp', import.meta.url).href,
    text :"Venu de la côte indienne, Harbor déferle sur le terrain grâce à une technologie antique qui lui permet de contrôler l'eau. Il déchaîne des torrents bouillonnants et de terribles lames d'eau pour protéger ses alliés et noyer ses adversaires.",
    video :"https://www.youtube.com/embed/qRao6FARFRo"
  },
  { id: 11, 
    name: 'Iso', 
    role: 'Duelliste', 
    difficulty: 'Facile', 
    image: new URL('../assets/images/icons/Iso_icon.webp', import.meta.url).href,
    text :"Venu de Chine et spécialiste de missions délicates, Iso se fond dans le flux de Radianite pour démanteler les réseaux ennemis. Capable de restructurer l'énergie ambiante en protection anti-balles, il ne dévie pas de la route vers son prochain duel à mort.",
    video :"https://www.youtube.com/embed/8OgcHAv6Jvk"
  },
  { id: 12, 
    name: 'Jett', 
    role: 'Duelliste', 
    difficulty: 'Facile', 
    image: new URL('../assets/images/icons/Jett_icon.webp', import.meta.url).href,
    text :"Représentante de sa patrie, la Corée du Sud, Jett dispose d'un style de combat basé sur l'agilité et l'esquive, qui lui permet de prendre des risques qu'elle seule peut se permettre de prendre. Elle tourne autour des affrontements et découpe ses ennemis avant même qu'ils ne s'en rendent compte.",
    video :"https://www.youtube.com/embed/xU2U73Tk-DM"
  },
  { id: 13, 
    name: 'Kay/o', 
    role: 'Initiateur', 
    difficulty: 'Facile', 
    image: new URL('../assets/images/icons/Kayo_icon.webp', import.meta.url).href,
    text :"KAY/O est une machine de guerre conçue dans un but précis : neutraliser les radiants. La neutralisation des compétences ennemies réduit les possibilités de riposte des adversaires, ce qui confère un avantage décisif à son équipe.",
    video :"https://www.youtube.com/embed/eU1l7eBy2_Y"
  },
  { id: 14, 
    name: 'Killjoy', 
    role: 'Sentinelle', 
    difficulty: 'Moyenne', 
    image: new URL('../assets/images/icons/Killjoy_icon.webp', import.meta.url).href,
    text :"Véritable génie originaire d'Allemagne, Killjoy sécurise et défend les positions clés sans effort grâce à son arsenal d'inventions. Si son équipement ne suffit pas à arrêter l'ennemi, ce sont les entraves de ses robots qui en feront du menu fretin.",
    video :"https://www.youtube.com/embed/ua-iIRQDY8g"
  },
  { id: 15, 
    name: 'Neon', 
    role: 'Duelliste', 
    difficulty: 'Moyenne', 
    image: new URL('../assets/images/icons/Neon_icon.webp', import.meta.url).href,
    text :"L'agent philippin, Neon, s'élance vers l'avant à une vitesse fulgurante, libérant de grosses décharges de radiance biomagnétique générées frénétiquement par son corps. Elle se lance à la poursuite des ennemis qui n'ont pas le temps de s'y préparer et les élimine aussi vite que l'éclair.",
    video :"https://www.youtube.com/embed/dtx8CgjRmqE"

  },
  { id: 16, 
    name: 'Omen', 
    role: 'Contrôleur', 
    difficulty: 'Facile', 
    image: new URL('../assets/images/icons/Omen_icon.webp', import.meta.url).href,
    text :"Véritable fantôme d'un souvenir, Omen chasse dans les ténèbres. Il aveugle les ennemis, se téléporte d'un bout à l'autre du champ de bataille et laisse la peur se répandre parmi ses adversaires qui se demandent qui sera sa prochaine victime.",
    video :"https://www.youtube.com/embed/_jJdWy6bDj4"
  },
  { id: 17, 
    name: 'Phoenix', 
    role: 'Duelliste', 
    difficulty: 'Moyenne', 
    image: new URL('../assets/images/icons/Phoenix_icon.webp', import.meta.url).href,
    text :"En provenance du Royaume-Uni, Phoenix illumine le champ de bataille avec ses pouvoirs astraux et son style de combat flamboyant. Peu importe que les renforts arrivent ou non, il fonce au combat quand il le décide.",
    video :"https://www.youtube.com/embed/ttJMFW2wUQM"
  },
  { id: 18, 
    name: 'Raze', 
    role: 'Duelliste', 
    difficulty: 'Moyenne', 
    image: new URL('../assets/images/icons/Raze_icon.webp', import.meta.url).href,
    text :"Armée de sa personnalité et de sa grosse artillerie, Raze fait une entrée explosive depuis le Brésil. Grâce à sa force brute, elle excelle à débusquer les ennemis retranchés et à faire le ménage dans les espaces étroits, le tout avec une bonne dose de « boum ».",
    video :"https://www.youtube.com/embed/2-uAL__pp_U"
  },
  { id: 19, 
    name: 'Reyna', 
    role: 'Duelliste', 
    difficulty: 'Facile', 
    image: new URL('../assets/images/icons/Reyna_icon.webp', import.meta.url).href,
    text :"Originaire du cœur du Mexique, Reyna est une experte des combats singuliers qui se renforce à chaque élimination qu'elle réussit. Son efficacité n'est limitée que par son habileté, ce qui la rend très dépendante de ses propres performances.",
    video :"https://www.youtube.com/embed/IzsQNYrq9AM"
  },
  { id: 20, 
    name: 'Sage', 
    role: 'Sentinelle', 
    difficulty: 'Facile', 
    image: new URL('../assets/images/icons/Sage_icon.webp', import.meta.url).href,
    text :"Véritable pilier originaire de Chine, Sage assure sa sécurité et celle de son équipe où qu'elle aille. Elle peut réanimer ses alliés tombés au combat et repousser les assauts ennemis pour offrir des oasis de tranquillité sur un champ de bataille infernal.",
    video :"https://www.youtube.com/embed/1aRwM_QsqQI"
  },
  { id: 21, 
    name: 'Skye', 
    role: 'Initiateur', 
    difficulty: 'Facile', 
    image: new URL('../assets/images/icons/Skye_icon.webp', import.meta.url).href,
    text :"Originaire d'Australie, Skye et sa bande de bêtes sauvages ouvrent la voie à travers les territoires hostiles. Grâce à ses créations qui entravent l'ennemi et à sa faculté à soigner les autres, l'équipe est plus forte et plus en sécurité quand elle compte Skye dans ses rangs.",
    video :"https://www.youtube.com/embed/C3QTyMXi-WE"
  },
  { id: 22, 
    name: 'Sova', 
    role: 'Initiateur', 
    difficulty: 'Moyenne', 
    image: new URL('../assets/images/icons/Sova_icon.webp', import.meta.url).href,
    text :"Né dans l'hiver éternel de la toundra russe, Sova traque, trouve et élimine ses ennemis avec une efficacité et une précision redoutables. Ses incroyables talents d'éclaireur et son arc personnalisé lui garantissent que sa cible ne fuira jamais très longtemps.",
    video :"https://www.youtube.com/embed/OZ76UP-c8Ao"
  },
  { id: 23, 
    name: 'Tejo', 
    role: 'Initiateur', 
    difficulty: 'Facile', 
    image: new URL('../assets/images/icons/Tejo_icon.webp', import.meta.url).href,
    text :"Originaire de Colombie, Tejo est un conseiller vétéran dans le domaine du renseignement. Son système de guidage balistique force les ennemis à perdre du terrain, voire la vie. Ses frappes chirurgicales lui permettent de garder les ennemis sous son emprise.",
    video :"https://www.youtube.com/embed/dRuRID5JoQY"
  },
  { id: 24, 
    name: 'Veto', 
    role: 'Sentinelle', 
    difficulty: 'Moyenne', 
    image: new URL('../assets/images/icons/Veto_icon.webp', import.meta.url).href,
    text :"Alimenté par une mutation génétique imparable, Veto, l'homme de main sénégalais, défie les règles du combat en neutralisant les pouvoirs et la technologie de ses adversaires. La seule chose que vous trouverez avec Veto sur le champ de bataille, c'est des armes.",
    video :"https://www.youtube.com/embed/2FLY-gn-hGQ"
  },
  { id: 25, 
    name: 'Viper', 
    role: 'Contrôleur', 
    difficulty: 'Moyenne', 
    image: new URL('../assets/images/icons/Viper_icon.webp', import.meta.url).href,
    text :"Viper est une chimiste américaine qui déploie un arsenal d'appareils toxiques pour contrôler le champ de bataille et entraver la vision des ennemis. Si les toxines ne suffisent pas à abattre sa proie, ses machinations finiront le travail.",
    video :"https://www.youtube.com/embed/9dOSy0EhLfQ"
  },
  { id: 26, 
    name: 'Vyse', 
    role: 'Sentinelle', 
    difficulty: 'Moyenne', 
    image: new URL('../assets/images/icons/Vyse_icon.webp', import.meta.url).href,
    text :"La génie du métal Vyse utilise le métal liquide pour isoler, piéger et désarmer ses ennemis. Par la ruse et la manipulation, elle force tous ses adversaires à craindre le champ de bataille lui-même.",
    video :"https://www.youtube.com/embed/btpWg1gDXIE"
  },
  { id: 27, 
    name: 'Waylay', 
    role: 'Duelliste', 
    difficulty: 'Moyenne', 
    image: new URL('../assets/images/icons/Waylay_icon.webp', import.meta.url).href,
    text :"Waylay, la prismatique radiante de Thaïlande, se transforme en particules de lumière pour filer sur le champ de bataille. Elle frappe ses cibles à l'aide d'éclats de lumière avant de se remettre à l'abri, le tout en un clin d'œil.",
    video :"https://www.youtube.com/embed/OHzUoFKPUB0"
  },
  { id: 28, 
    name: 'Yoru', 
    role: 'Duelliste', 
    difficulty: 'Difficile', 
    image: new URL('../assets/images/icons/Yoru_icon.webp', import.meta.url).href,
    text :"Le Japonais Yoru perce des trous dans la réalité pour s'infiltrer derrière les lignes ennemies sans se faire repérer. En faisant preuve d'autant de ruse que d'agressivité, il prend ses cibles par surprise avant qu'elles n'aient le temps de se retourner.",
    video :"https://www.youtube.com/embed/GdOEQv-zQVw"
  }
]
</script>