<script>
export default [
  
  { id: 1, name: 'Astra', role: 'Contrôleur', difficulty: 'Difficile' },
  { id: 2, name: 'Breach', role: 'Initiateur', difficulty: 'Moyenne' },
  { id: 3, name: 'Brimstone', role: 'Contrôleur', difficulty: 'Facile' },
  { id: 4, name: 'Chamber', role: 'Sentinelle', difficulty: 'Facile' },
  { id: 5, name: 'Clove', role: 'Contrôleur', difficulty: 'Facile' },
  { id: 6, name: 'Cypher', role: 'Sentinelle', difficulty: 'Moyenne' },
  { id: 7, name: 'Deadlock', role: 'Sentinelle', difficulty: 'Moyenne' },
  { id: 8, name: 'Fade', role: 'Initiateur', difficulty: 'Moyenne' },
  { id: 9, name: 'Gekko', role: 'Initiateur', difficulty: 'Moyenne' },
  { id: 10, name: 'Harbor', role: 'Contrôleur', difficulty: 'Moyenne' },
  { id: 11, name: 'Iso', role: 'Duelliste', difficulty: 'Facile' },
  { id: 12, name: 'Jett', role: 'Duelliste', difficulty: 'Facile' },
  { id: 13, name: 'Kay/o', role: 'Initiateur', difficulty: 'Facile' },
  { id: 14, name: 'Killjoy', role: 'Sentinelle', difficulty: 'Moyenne' },
  { id: 15, name: 'Neon', role: 'Duelliste', difficulty: 'Moyenne' },
  { id: 16, name: 'Omen', role: 'Contrôleur', difficulty: 'Facile' },
  { id: 17, name: 'Phoenix', role: 'Duelliste', difficulty: 'Moyenne' },
  { id: 18, name: 'Raze', role: 'Duelliste', difficulty: 'Moyenne' },
  { id: 19, name: 'Reyna', role: 'Duelliste', difficulty: 'Facile' },
  { id: 20, name: 'Sage', role: 'Sentinelle', difficulty: 'Facile' },
  { id: 21, name: 'Skye', role: 'Initiateur', difficulty: 'Facile' },
  { id: 22, name: 'Sova', role: 'Initiateur', difficulty: 'Moyenne' },
  { id: 23, name: 'Tejo', role: 'Initiateur', difficulty: 'Facile' },
  { id: 24, name: 'Veto', role: 'Sentinelle', difficulty: 'Moyenne' },
  { id: 25, name: 'Viper', role: 'Contrôleur', difficulty: 'Moyenne' },
  { id: 26, name: 'Vyse', role: 'Sentinelle', difficulty: 'Moyenne' },
  { id: 27, name: 'Waylay', role: 'Duelliste', difficulty: 'Moyenne' },
  { id: 28, name: 'Yoru', role: 'Duelliste', difficulty: 'Difficile' },
]
</script>